#[allow(unused)]
use crate::Adapter;
use crate::Uuid;
use std::collections::HashMap;

/// A platform-specific device identifier.
/// On Android it contains the Bluetooth address in the format `AB:CD:EF:01:23:45`.
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct DeviceId(pub(crate) String);

impl std::fmt::Display for DeviceId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.0, f)
    }
}

/// Events generated by [`Adapter::events`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum AdapterEvent {
    /// The adapter has become available (powered on and ready to use)
    Available,
    /// The adapter has become unavailable (powered off or otherwise disabled)
    Unavailable,
}

/// Events generated by [`Adapter::device_connection_events`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ConnectionEvent {
    /// The device has disconnected from the host system
    Disconnected,
    /// The device has connected to the host system
    Connected,
}

/// Represents a device discovered during a scan operation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AdvertisingDevice {
    /// The source of the advertisement
    pub device: crate::Device,
    /// The advertisment data
    pub adv_data: AdvertisementData,
    /// The signal strength in dBm of the received advertisement packet
    pub rssi: Option<i16>,
}

/// Data included in a Bluetooth advertisement or scan reponse.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AdvertisementData {
    /// The (possibly shortened) local name of the device (CSS §A.1.2)
    pub local_name: Option<String>,
    /// Manufacturer specific data (CSS §A.1.4)
    pub manufacturer_data: Option<ManufacturerData>,
    /// Advertised GATT service UUIDs (CSS §A.1.1)
    pub services: Vec<Uuid>,
    /// Service associated data (CSS §A.1.11)
    pub service_data: HashMap<Uuid, Vec<u8>>,
    /// Transmitted power level (CSS §A.1.5)
    pub tx_power_level: Option<i16>,
    /// Set to true for connectable advertising packets
    pub is_connectable: bool,
}

/// Manufacturer specific data included in Bluetooth advertisements.
///
/// See the Bluetooth Core Specification Supplement §A.1.4 for details.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ManufacturerData {
    /// Company identifier (defined [here](https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/))
    pub company_id: u16,
    /// Manufacturer specific data
    pub data: Vec<u8>,
}

/// GATT characteristic properties as defined in the Bluetooth Core Specification, Vol 3, Part G, §3.3.1.1.
///
/// Extended properties are also included as defined in §3.3.3.1.
#[allow(missing_docs)]
#[non_exhaustive]
#[derive(Copy, Clone, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct CharacteristicProperties {
    pub broadcast: bool,
    pub read: bool,
    pub write_without_response: bool,
    pub write: bool,
    pub notify: bool,
    pub indicate: bool,
    pub authenticated_signed_writes: bool,
    pub extended_properties: bool,
    pub reliable_write: bool,
    pub writable_auxiliaries: bool,
}

impl CharacteristicProperties {
    /// Raw transmutation from [`u32`].
    ///
    /// Extended properties are in the upper bits.
    pub fn from_bits(bits: u32) -> Self {
        CharacteristicProperties {
            broadcast: (bits & (1 << 0)) != 0,
            read: (bits & (1 << 1)) != 0,
            write_without_response: (bits & (1 << 2)) != 0,
            write: (bits & (1 << 3)) != 0,
            notify: (bits & (1 << 4)) != 0,
            indicate: (bits & (1 << 5)) != 0,
            authenticated_signed_writes: (bits & (1 << 6)) != 0,
            extended_properties: (bits & (1 << 7)) != 0,
            reliable_write: (bits & (1 << 8)) != 0,
            writable_auxiliaries: (bits & (1 << 9)) != 0,
        }
    }

    /// Raw transmutation to [`u32`].
    ///
    /// Extended properties are in the upper bits.
    pub fn to_bits(self) -> u32 {
        u32::from(self.broadcast)
            | (u32::from(self.read) << 1)
            | (u32::from(self.write_without_response) << 2)
            | (u32::from(self.write) << 3)
            | (u32::from(self.notify) << 4)
            | (u32::from(self.indicate) << 5)
            | (u32::from(self.authenticated_signed_writes) << 6)
            | (u32::from(self.extended_properties) << 7)
            | (u32::from(self.reliable_write) << 8)
            | (u32::from(self.writable_auxiliaries) << 9)
    }
}
